# Regenerate experimental copies from production. No production dispatch is changed.
$ErrorActionPreference='Stop'
$root=Split-Path (Split-Path $PSScriptRoot)
$source=[IO.File]::ReadAllText((Join-Path $root 'tests/LegacySingleThreadSimd/Avx2BigIntegerPower.cs'))
$source=$source.Replace('Avx2BigIntegerPower','AuditKernel').Replace('private static void Accumulate','internal static void Accumulate')
[IO.File]::WriteAllText((Join-Path $PSScriptRoot 'AuditKernel.generated.cs'),$source)
$source=[IO.File]::ReadAllText((Join-Path $root 'tests/LegacySingleThreadSimd/SingleThreadBigIntegerPower.cs'))
$source=$source.Replace('SingleThreadBigIntegerPower','CandidatePower').Replace('bool useCustomWindow = useSimd && IsSupported;', 'bool useCustomWindow = useSimd && IsSupported;'+"`n"+'        using var squareWorkspace = new CandidateSquare(CandidateSquare.Limit);')
$source=$source.Replace('MaximumAccumulatorLimbCount','(CandidateSquare.Limit * 2 + 8)')
$source=$source.Replace('CanSquareInCustomWindow(', 'CandidateSquare.CanSquare(').Replace('CanMultiplyInCustomWindow(', 'CandidateSquare.CanMultiply(').Replace('SquareMagnitude(', 'squareWorkspace.Square(')
$source=$source.Replace('length >= PredictiveRuntimeWindowHandoffMinimumLimbCount','length > CandidateSquare.Limit').Replace('length >= EarlyRuntimeBatchHandoffMinimumLimbCount','length > CandidateSquare.Limit')
[IO.File]::WriteAllText((Join-Path $PSScriptRoot 'CandidatePower.generated.cs'),$source)
$source=[IO.File]::ReadAllText((Join-Path $root 'tests/LegacySingleThreadSimd/SingleThreadBigIntegerPower.cs'))
$source=$source.Replace('SingleThreadBigIntegerPower','ProfileCurrent').Replace('BigInteger.Pow(', 'Measure.Pow(')
$source=[regex]::Replace($source,'resultBigInteger \*=\s*resultBigInteger;', 'resultBigInteger = Measure.Square(resultBigInteger);')
[IO.File]::WriteAllText((Join-Path $PSScriptRoot 'ProfileCurrent.generated.cs'),$source)
