namespace MathSolver.Services.Localization;

/// <summary>Stable bilingual strings for math puzzle controls and grading.</summary>
internal static class QuizLocalizationOverrides
{
    private static readonly IReadOnlyDictionary<string, string> Vietnamese =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Quiz.ShowDiagram"] = "Xem sơ đồ",
            ["Quiz.ComparisonSubtype"] = "So sánh < = >",
            ["Quiz.Elementary.IntegerCompare"] = "So sánh số nguyên",
            ["Quiz.ComparisonQuestionTitle"] = "Điền dấu so sánh thích hợp",
            ["Quiz.ComparisonTrueFalseTitle"] = "So sánh sau đúng hay sai?",
            ["Quiz.ComparisonEssayHint"] = "Nhập dấu >, <, = hoặc cả dòng so sánh. Không bắt buộc lời giải hay phép tính riêng.",
            ["Quiz.ComparisonEssayPlaceholder"] = "Dấu >, <, = hoặc dòng so sánh hai số",
            ["Quiz.HideDiagram"] = "Ẩn sơ đồ",
            ["Quiz.EnlargeDiagram"] = "Phóng to hình",
            ["Quiz.CloseDiagram"] = "Đóng hình",
            ["Quiz.DiagramZoom"] = "Mức phóng to",
            ["Quiz.DiagramNotToScale"] = "Hình minh họa không theo tỉ lệ số đo.",
            ["Quiz.ProblemTwoNumbers"] = "Tìm hai số",
            ["Quiz.ProblemMeasurement"] = "Đo lường",
            ["Quiz.ProblemTime"] = "Thời gian",
            ["Quiz.ProblemRemainder"] = "Chia có dư",
            ["Quiz.ProblemDecimal"] = "Số thập phân",
            ["Quiz.ProblemMultiStep"] = "Bài toán nhiều bước",
            ["Quiz.Elementary.MapScale"] = "Tỉ lệ bản đồ",
            ["Quiz.Elementary.ReadPictograph"] = "Đọc biểu đồ tranh",
            ["Quiz.Elementary.RecognizeShape"] = "Nhận diện hình",
            ["Quiz.Elementary.MultiStepAddSubtract"] = "Gộp, bớt và tìm lượng ban đầu",
            ["Quiz.Elementary.MultiStepEqualGroups"] = "Các nhóm bằng nhau và điều chỉnh",
            ["Quiz.Elementary.MultiStepRemaining"] = "Tìm lượng còn lại qua nhiều bước",
            ["Quiz.Elementary.MultiStepShare"] = "Tổng hợp lượng rồi chia đều",
            ["Quiz.ProblemFractionSkills"] = "Kĩ năng phân số",
            ["Quiz.ProblemData"] = "Bảng và biểu đồ",
            ["Quiz.ProblemProbability"] = "Khả năng xảy ra",
            ["Quiz.ProblemVisualGeometry"] = "Hình học trực quan",
            ["Quiz.Elementary.SumDifference"] = "Tổng – hiệu",
            ["Quiz.Elementary.SumRatio"] = "Tổng – tỉ",
            ["Quiz.Elementary.DifferenceRatio"] = "Hiệu – tỉ",
            ["Quiz.Elementary.LengthConversion"] = "Đổi đơn vị độ dài",
            ["Quiz.Elementary.MassConversion"] = "Đổi đơn vị khối lượng",
            ["Quiz.Elementary.CapacityConversion"] = "Đổi đơn vị dung tích",
            ["Quiz.Elementary.AreaConversion"] = "Đổi đơn vị diện tích",
            ["Quiz.Elementary.VolumeConversion"] = "Đổi đơn vị thể tích",
            ["Quiz.Elementary.MixedLength"] = "Số đo có hai đơn vị",
            ["Quiz.Elementary.ElapsedTime"] = "Thời gian trôi qua",
            ["Quiz.Elementary.TimeAddition"] = "Đổi giờ và phút",
            ["Quiz.Elementary.ReadClock"] = "Đọc đồng hồ",
            ["Quiz.Elementary.Calendar"] = "Tính số ngày",
            ["Quiz.Elementary.QuotientRemainder"] = "Thương và số dư",
            ["Quiz.Elementary.FullGroups"] = "Số nhóm đầy",
            ["Quiz.Elementary.MinimumGroups"] = "Số nhóm tối thiểu",
            ["Quiz.Elementary.Leftovers"] = "Phần còn lại",
            ["Quiz.Elementary.DecimalAdd"] = "Cộng số thập phân",
            ["Quiz.Elementary.DecimalSubtract"] = "Trừ số thập phân",
            ["Quiz.Elementary.DecimalMultiply"] = "Nhân số thập phân",
            ["Quiz.Elementary.DecimalDivide"] = "Chia số thập phân",
            ["Quiz.Elementary.DecimalRound"] = "Làm tròn",
            ["Quiz.Elementary.DecimalCompare"] = "So sánh số thập phân",
            ["Quiz.Elementary.ReduceFraction"] = "Rút gọn phân số",
            ["Quiz.Elementary.CompareFractions"] = "So sánh phân số",
            ["Quiz.Elementary.MixedNumber"] = "Đổi sang hỗn số",
            ["Quiz.Elementary.CommonDenominator"] = "Quy đồng mẫu số",
            ["Quiz.Elementary.FractionOfNumber"] = "Tìm phân số của một số",
            ["Quiz.Elementary.WholeFromFraction"] = "Tìm số khi biết một phần",
            ["Quiz.Elementary.ReadTable"] = "Đọc bảng",
            ["Quiz.Elementary.ReadBarChart"] = "Đọc biểu đồ cột",
            ["Quiz.Elementary.ReadPieChart"] = "Đọc biểu đồ tròn",
            ["Quiz.Elementary.ChartTotal"] = "Tổng các giá trị",
            ["Quiz.Elementary.ChartDifference"] = "Chênh lệch các giá trị",
            ["Quiz.Elementary.Likelihood"] = "Chắc Chắn, Có Thể, Không Thể",
            ["Quiz.Elementary.ExperimentalProbability"] = "Phân số qua thử nghiệm",
            ["Quiz.Elementary.ClassifyAngle"] = "Nhận biết góc",
            ["Quiz.Elementary.ParallelLines"] = "Hai đường song song",
            ["Quiz.Elementary.PerpendicularLines"] = "Hai đường vuông góc",
            ["Quiz.Elementary.CountSides"] = "Đếm cạnh",
            ["Quiz.Elementary.RectangleSide"] = "Tìm cạnh còn thiếu",
            ["Quiz.Elementary.CompositeArea"] = "Diện tích hình ghép",
            ["Quiz.ElementaryTypeTitle"] = "Chọn dạng bài (hoặc hỗn hợp)",
            ["Quiz.ElementaryEssayHint"] = "Có thể gộp hoặc tách bước; mỗi phép tính một dòng. Ghi đủ kết quả và đơn vị. Nếu có hai đáp số, ngăn cách bằng dấu chấm phẩy và có thể ghi nhãn từng kết quả.",
            ["Quiz.ElementaryEssayPlaceholder"] = "Lời giải: nêu đơn vị hoặc đối tượng cần tìm.\nPhép tính = kết quả\nĐáp số: kết quả thứ nhất; kết quả thứ hai",
            ["Quiz.ElementaryAnswerPlaceholder"] = "Phép tính (nếu cần) = kết quả\nĐáp số: …",
            ["Quiz.ClockAnswerLabel"] = "Đáp số: giờ và phút",
            ["Quiz.ClockAnswerHint"] = "Bắt buộc ghi Đáp số: trước giờ và phút, ví dụ: Đáp số: Giờ: 3, phút: 35 hoặc Đáp số: 3 giờ 35 phút. Không cần lời giải hay phép tính.",
            ["Quiz.ClockAnswerPlaceholder"] = "Đáp số: Giờ: …, phút: …\nHoặc: Đáp số: … giờ … phút",
            ["Quiz.ClockEssayHint"] = "Ghi lời giải và phép tính cho thời gian cần tìm, rồi ghi đáp số theo mẫu: Đáp số: Giờ: …, phút: … hoặc Đáp số: … giờ … phút.",
            ["Quiz.ClockEssayPlaceholder"] = "Lời giải và phép tính cho thời gian cần tìm\nĐáp số: Giờ: …, phút: …\nHoặc: Đáp số: … giờ … phút",
            ["Quiz.PracticeSubtitleAlgorithmOnly"] = "Thuật toán • Đúng/Sai • 4 đáp án • Tự luận",
            ["Quiz.ModeTitle"] = "2. Chọn kiểu câu hỏi",
            ["Quiz.ModeTitleAlgorithmOnly"] = "1. Chọn kiểu câu hỏi",
            ["Quiz.CurriculumTitle"] = "3. Chọn mức độ",
            ["Quiz.CurriculumTitleAlgorithmOnly"] = "2. Chọn mức độ",
            ["Quiz.CurriculumHintMixed"] = "Hỗn hợp có bộ quy tắc riêng: số sao quyết định dạng toán được phép xuất hiện, phạm vi số và trọng số ngẫu nhiên.",
            ["Quiz.CurriculumHintSkill"] = "Mỗi dạng toán có lộ trình riêng theo số sao; độ khó xét dữ kiện, quan hệ và các bước suy luận cần dùng.",
            ["Quiz.CurriculumMinimumTier"] = "Dạng này bắt đầu từ mức {0}.",
            ["Quiz.EssayMode"] = "✍️ Tự luận",
            ["Quiz.EssayQuestionTitle"] = "Thực hiện phép tính",
            ["Quiz.EssaySolutionLabel"] = "Lời giải",
            ["Quiz.EssaySolutionPlaceholder"] = "Viết câu lời giải có đúng đơn vị hoặc đối tượng cần tìm (bắt buộc)",
            ["Quiz.EssayCombinedLabel"] = "Lời giải, phép tính và đáp số",
            ["Quiz.EssayCombinedNumericLabel"] = "Phép tính và đáp số",
            ["Quiz.EssayCombinedPlaceholder"] = "Viết câu lời giải, rồi xuống dòng để ghi phép tính và đáp số.",
            ["Quiz.EssayCombinedAnswerPlaceholder"] = "Đáp số: …",
            ["Quiz.EssayCombinedAnswerHint"] = "Viết tất cả trong ô trên. Ghi đáp số trên dòng cuối theo mẫu \"Đáp số: …\".",
            ["Quiz.EssayEquationLabel"] = "Phép tính",
            ["Quiz.EssayEquationPlaceholder"] = "Ví dụ: 5 × 6 = 30",
            ["Quiz.AverageEssayEquationPlaceholder"] = "Ví dụ: (2 + 4 + 6 + 8) ÷ 4 = 5",
            ["Quiz.PercentageRatioEssayEquationPlaceholder"] = "Ví dụ: 20 ÷ 80 × 100 = 25",
            ["Quiz.PercentageValueEssayEquationPlaceholder"] = "Ví dụ: 200 × 25 ÷ 100 = 50",
            ["Quiz.PercentageWholeEssayEquationPlaceholder"] = "Ví dụ: 50 × 100 ÷ 25 = 200",
            ["Quiz.GeometryEssayEquationPlaceholder"] = "Ví dụ: (12 + 8) × 2 = 40",
            ["Quiz.EssayAnswerLabel"] = "Đáp số",
            ["Quiz.EssayAnswerPlaceholder"] = "Ví dụ: 30 cây bút",
            ["Quiz.EssayValidationHint"] = "Bắt buộc điền lời giải có đúng đơn vị hoặc đối tượng cần tìm. Ứng dụng vẫn chấm phép tính, kết quả và đơn vị đáp số.",
            ["Quiz.EssayValidationHintAlgorithm"] = "Ứng dụng chấm hai số dữ kiện, phép toán, kết quả và giá trị đáp số.",
            ["Quiz.EssayValidationHintAlgorithmWordProblem"] = "Bắt buộc điền lời giải có đúng đơn vị hoặc đối tượng cần tìm (ví dụ: kg, gam, đồng, trứng, sản phẩm, tiền). Ứng dụng vẫn chấm phép tính và đáp số.",
            ["Quiz.EssayEquationUnitHint"] = "Ghi đúng đơn vị ngay sau kết quả trong phép tính.",
            ["Quiz.GeometryEssayValidationHint"] = "Bắt buộc điền lời giải có đúng đơn vị hoặc tên đối tượng hình học. Ứng dụng chấm công thức thay số, kết quả và đúng bậc đơn vị.",
            ["Quiz.SubmitEssayAnswer"] = "📝 Chấm bài",
            ["Quiz.EssayCorrectFeedback"] = "Chính xác! Lời giải, phép tính và đáp số đều đúng.",
            ["Quiz.EssayCorrectFeedbackNumeric"] = "Chính xác! Phép tính và đáp số đều đúng.",
            ["Quiz.EssaySolutionRequired"] = "Em chưa điền lời giải. Phần lời giải là bắt buộc đối với bài toán có lời văn.",
            ["Quiz.EssaySolutionContentIncorrect"] = "Lời giải chưa nêu đúng đơn vị hoặc đối tượng cần tìm trong đề bài.",
            ["Quiz.EssayEquationAndAnswerIncorrect"] = "Phép tính và đáp số đều chưa đúng.",
            ["Quiz.EssayEquationFormatIncorrect"] = "Phép tính chưa đúng định dạng. Hãy nhập đầy đủ như 5 × 6 = 30.",
            ["Quiz.EssayEquationIncorrect"] = "Phép tính chưa đúng dữ kiện, phép toán hoặc kết quả.",
            ["Quiz.EssayEquationUnitIncorrect"] = "Kết quả trong phép tính thiếu đơn vị hoặc ghi sai đơn vị so với đáp số.",
            ["Quiz.EssayAnswerIncorrect"] = "Phép tính đúng nhưng đáp số chưa đúng.",
            ["Quiz.EssayAnswerUnitIncorrect"] = "Giá trị đáp số đúng nhưng đơn vị chưa phù hợp với đề bài.",
            ["Quiz.RegenerateQuestion"] = "🔄 Tạo đề lại",
            ["Quiz.OperationTitle"] = "4. Chọn bài toán",
            ["Quiz.OperationTitleAlgorithmOnly"] = "3. Chọn bài toán",
            ["Quiz.OperationMixed"] = "Hỗn hợp",
            ["Quiz.ProblemBasic"] = "Cơ bản + − × ÷",
            ["Quiz.ProblemFraction"] = "Phân số ½",
            ["Quiz.ProblemExpression"] = "Tính giá trị biểu thức",
            ["Quiz.ExpressionTypeTitle"] = "Chọn dạng biểu thức",
            ["Quiz.ExpressionInteger"] = "Số nguyên – Không ngoặc",
            ["Quiz.ExpressionIntegerBrackets"] = "Số nguyên – Có ngoặc",
            ["Quiz.ExpressionFraction"] = "Phân số – Không ngoặc",
            ["Quiz.ExpressionFractionBrackets"] = "Phân số – Có ngoặc",
            ["Quiz.ExpressionDifficultyHint"] = "1–5 sao: 3–7 số. Dạng có ngoặc thêm 1–5 cặp ngoặc tương ứng; mỗi phân số tính là một số.",
            ["Quiz.ExpressionQuestionTitle"] = "Tính giá trị biểu thức",
            ["Quiz.ExpressionEssayHint"] = "Nhập biểu thức và kết quả sau dấu =, rồi điền đáp số. Không cần câu lời giải hay đơn vị. Chấp nhận các phân số tương đương.",
            ["Quiz.AverageIndirectEssayHint"] = "Có thể gộp thành một phép tính hoặc giải 2–3 bước. Mỗi phép tính có dấu = viết trên một dòng; được dùng kết quả bước trước. Không bắt buộc câu lời giải riêng và đơn vị ở từng bước trung gian. Ghi đúng đơn vị ở phép tính cuối và đáp số.",
            ["Quiz.ExpressionIntegerPlaceholder"] = "Ví dụ: 1 + 2 + 3 = 6",
            ["Quiz.ExpressionFractionPlaceholder"] = "Ví dụ: (1/2 + 1/3) × 3/5 = 1/2",
            ["Quiz.ExpressionAnswerPlaceholder"] = "Ví dụ: 6",
            ["Quiz.BasicOperationTitle"] = "Chọn phép tính cơ bản",
            ["Quiz.FractionOperationTitle"] = "Chọn phép tính phân số",
            ["Quiz.ProblemGeometry"] = "Hình học △ □ ◯",
            ["Quiz.GeometryMeasurementTitle"] = "Chọn đại lượng cần tính",
            ["Quiz.GeometryPerimeter"] = "Chu vi",
            ["Quiz.GeometryArea"] = "Diện tích",
            ["Quiz.GeometryVolume"] = "Thể tích",
            ["Quiz.GeometryLateralArea"] = "Diện tích xung quanh",
            ["Quiz.GeometryTotalArea"] = "Diện tích toàn phần",
            ["Quiz.ProblemFindX"] = "Tìm 𝑥",
            ["Quiz.ProblemProportion"] = "Tỉ lệ thuận / nghịch ↗↘",
            ["Quiz.ProblemMotion"] = "Chuyển động ➜⏱️",
            ["Quiz.MotionQuestionTitle"] = "Bài toán chuyển động",
            ["Quiz.MotionTypeTitle"] = "Chọn dạng chuyển động",
            ["Quiz.MotionBasic"] = "Cơ bản – Một vật chuyển động",
            ["Quiz.MotionChasing"] = "Hai vật cùng chiều (đuổi nhau / đuổi kịp)",
            ["Quiz.MotionMeeting"] = "Hai vật ngược chiều (gặp nhau)",
            ["Quiz.MotionRiver"] = "Chuyển động trên dòng nước (xuôi dòng – ngược dòng)",
            ["Quiz.MotionEssayValidationHint"] = "Bắt buộc điền lời giải có đúng đơn vị hoặc đối tượng cần tìm. Phép tính phải đúng dữ kiện chuyển động và đáp số kèm đúng đơn vị.",
            ["Quiz.MotionEssayEquationPlaceholder"] = "Ví dụ: 120 ÷ (60 + 40) = 1",
            ["Quiz.ProportionTypeTitle"] = "Chọn dạng tỉ lệ",
            ["Quiz.ProportionDirect"] = "↗ Tỉ lệ thuận",
            ["Quiz.ProportionInverse"] = "↘ Tỉ lệ nghịch",
            ["Quiz.ProportionQuestionTitle"] = "Bài toán tỉ lệ thuận / nghịch",
            ["Quiz.ProportionEssayValidationHint"] = "Bắt buộc điền lời giải có đúng đơn vị hoặc đối tượng cần tìm. Ứng dụng chấm dữ kiện tỉ lệ, công thức tính và đáp số.",
            ["Quiz.ProportionEssayEquationPlaceholder"] = "Ví dụ: 24 ÷ 4 × 6 = 36",
            ["Quiz.FractionQuestionTitle"] = "Bài toán phân số",
            ["Quiz.FractionEssayEquationPlaceholder"] = "Ví dụ: 1/2 + 1/4 = 3/4",
            ["Quiz.FractionEssayValidationHint"] = "Ứng dụng chấm hai phân số, phép tính và kết quả đã rút gọn.",
            ["Quiz.FractionEssayAnswerPlaceholder"] = "Ví dụ: 3/4 mét vải",
            ["Quiz.FindXQuestionTitle"] = "Tìm giá trị của 𝑥",
            ["Quiz.FindXEssayValidationHint"] = "Ứng dụng chấm phép tính ngược và giá trị 𝑥; không cần câu lời giải cho phương trình số.",
            ["Quiz.FindXEssayEquationPlaceholder"] = "Ví dụ: 12 − 5 = 7",
            ["Quiz.WordProblemTitle"] = "Bài toán có lời văn",
            ["Quiz.PresentedAnswer"] = "Đáp án: {0} {1}",
            ["Quiz.SolutionTitle"] = "Lời giải"
        };

    private static readonly IReadOnlyDictionary<string, string> English =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Quiz.ShowDiagram"] = "Show diagram",
            ["Quiz.ComparisonSubtype"] = "Compare < = >",
            ["Quiz.Elementary.IntegerCompare"] = "Compare integers",
            ["Quiz.ComparisonQuestionTitle"] = "Fill in the correct comparison sign",
            ["Quiz.ComparisonTrueFalseTitle"] = "Is this comparison true or false?",
            ["Quiz.ComparisonEssayHint"] = "Enter >, <, = or the complete comparison. No separate explanation or calculation is required.",
            ["Quiz.ComparisonEssayPlaceholder"] = ">, <, = or the comparison of the two values",
            ["Quiz.HideDiagram"] = "Hide diagram",
            ["Quiz.EnlargeDiagram"] = "Enlarge diagram",
            ["Quiz.CloseDiagram"] = "Close diagram",
            ["Quiz.DiagramZoom"] = "Zoom level",
            ["Quiz.DiagramNotToScale"] = "Illustration is not drawn to scale.",
            ["Quiz.ProblemTwoNumbers"] = "Find two numbers",
            ["Quiz.ProblemMeasurement"] = "Measurement",
            ["Quiz.ProblemTime"] = "Time",
            ["Quiz.ProblemRemainder"] = "Division with remainder",
            ["Quiz.ProblemDecimal"] = "Decimals",
            ["Quiz.ProblemMultiStep"] = "Multi-step word problems",
            ["Quiz.Elementary.MapScale"] = "Map scale",
            ["Quiz.Elementary.ReadPictograph"] = "Read a pictograph",
            ["Quiz.Elementary.RecognizeShape"] = "Recognize a shape",
            ["Quiz.Elementary.MultiStepAddSubtract"] = "Combine, remove and recover an initial amount",
            ["Quiz.Elementary.MultiStepEqualGroups"] = "Equal groups and adjustments",
            ["Quiz.Elementary.MultiStepRemaining"] = "Find the remainder in several steps",
            ["Quiz.Elementary.MultiStepShare"] = "Combine quantities and share equally",
            ["Quiz.ProblemFractionSkills"] = "Fraction skills",
            ["Quiz.ProblemData"] = "Tables and charts",
            ["Quiz.ProblemProbability"] = "Likelihood",
            ["Quiz.ProblemVisualGeometry"] = "Visual geometry",
            ["Quiz.Elementary.SumDifference"] = "Sum and difference",
            ["Quiz.Elementary.SumRatio"] = "Sum and ratio",
            ["Quiz.Elementary.DifferenceRatio"] = "Difference and ratio",
            ["Quiz.Elementary.LengthConversion"] = "Length conversion",
            ["Quiz.Elementary.MassConversion"] = "Mass conversion",
            ["Quiz.Elementary.CapacityConversion"] = "Capacity conversion",
            ["Quiz.Elementary.AreaConversion"] = "Area conversion",
            ["Quiz.Elementary.VolumeConversion"] = "Volume conversion",
            ["Quiz.Elementary.MixedLength"] = "Mixed length units",
            ["Quiz.Elementary.ElapsedTime"] = "Elapsed time",
            ["Quiz.Elementary.TimeAddition"] = "Hours and minutes",
            ["Quiz.Elementary.ReadClock"] = "Read a clock",
            ["Quiz.Elementary.Calendar"] = "Calendar intervals",
            ["Quiz.Elementary.QuotientRemainder"] = "Quotient and remainder",
            ["Quiz.Elementary.FullGroups"] = "Full groups",
            ["Quiz.Elementary.MinimumGroups"] = "Minimum groups",
            ["Quiz.Elementary.Leftovers"] = "Leftovers",
            ["Quiz.Elementary.DecimalAdd"] = "Decimal addition",
            ["Quiz.Elementary.DecimalSubtract"] = "Decimal subtraction",
            ["Quiz.Elementary.DecimalMultiply"] = "Decimal multiplication",
            ["Quiz.Elementary.DecimalDivide"] = "Decimal division",
            ["Quiz.Elementary.DecimalRound"] = "Rounding",
            ["Quiz.Elementary.DecimalCompare"] = "Compare decimals",
            ["Quiz.Elementary.ReduceFraction"] = "Reduce fractions",
            ["Quiz.Elementary.CompareFractions"] = "Compare fractions",
            ["Quiz.Elementary.MixedNumber"] = "Convert to a mixed number",
            ["Quiz.Elementary.CommonDenominator"] = "Common denominators",
            ["Quiz.Elementary.FractionOfNumber"] = "Fraction of a quantity",
            ["Quiz.Elementary.WholeFromFraction"] = "Find the whole from a fraction",
            ["Quiz.Elementary.ReadTable"] = "Read a table",
            ["Quiz.Elementary.ReadBarChart"] = "Read a bar chart",
            ["Quiz.Elementary.ReadPieChart"] = "Read a pie chart",
            ["Quiz.Elementary.ChartTotal"] = "Total values",
            ["Quiz.Elementary.ChartDifference"] = "Difference between values",
            ["Quiz.Elementary.Likelihood"] = "Certain, possible, impossible",
            ["Quiz.Elementary.ExperimentalProbability"] = "Fraction of trial outcomes",
            ["Quiz.Elementary.ClassifyAngle"] = "Identify angles",
            ["Quiz.Elementary.ParallelLines"] = "Parallel lines",
            ["Quiz.Elementary.PerpendicularLines"] = "Perpendicular lines",
            ["Quiz.Elementary.CountSides"] = "Count sides",
            ["Quiz.Elementary.RectangleSide"] = "Find a missing side",
            ["Quiz.Elementary.CompositeArea"] = "Composite area",
            ["Quiz.ElementaryTypeTitle"] = "Choose a skill (or mixed)",
            ["Quiz.ElementaryEssayHint"] = "Combine or split steps; write one equation per line. Include all results and units. Separate two answers with a semicolon; labels may identify each result.",
            ["Quiz.ElementaryEssayPlaceholder"] = "Solution: name the unit or quantity to find.\nExpression = result\nAnswer: first result; second result",
            ["Quiz.ElementaryAnswerPlaceholder"] = "Expression (if needed) = result\nAnswer: …",
            ["Quiz.ClockAnswerLabel"] = "Answer: hour and minute",
            ["Quiz.ClockAnswerHint"] = "An Answer: label is required before the hour and minute, for example: Answer: Hour: 3, minute: 35 or Answer: 3 hours 35 minutes. No explanation or calculation is needed.",
            ["Quiz.ClockAnswerPlaceholder"] = "Answer: Hour: …, minute: …\nOr: Answer: … hours … minutes",
            ["Quiz.ClockEssayHint"] = "Write the explanation and calculations for the requested time, then enter the final answer as: Answer: Hour: …, minute: … or Answer: … hours … minutes.",
            ["Quiz.ClockEssayPlaceholder"] = "Explanation and calculations for the requested time\nAnswer: Hour: …, minute: …\nOr: Answer: … hours … minutes",
            ["Quiz.PracticeSubtitleAlgorithmOnly"] = "Algorithm • True/False • 4 choices • Written answer",
            ["Quiz.ModeTitle"] = "2. Choose a question mode",
            ["Quiz.ModeTitleAlgorithmOnly"] = "1. Choose a question mode",
            ["Quiz.CurriculumTitle"] = "3. Choose a difficulty level",
            ["Quiz.CurriculumTitleAlgorithmOnly"] = "2. Choose a difficulty level",
            ["Quiz.CurriculumHintMixed"] = "Mixed mode has its own rules: stars control which skills may appear, number ranges, and random weights.",
            ["Quiz.CurriculumHintSkill"] = "Each skill follows a star-based progression using facts, relations and reasoning steps.",
            ["Quiz.CurriculumMinimumTier"] = "This skill starts at {0}.",
            ["Quiz.EssayMode"] = "✍️ Written",
            ["Quiz.EssayQuestionTitle"] = "Calculate the result",
            ["Quiz.EssaySolutionLabel"] = "Solution sentence",
            ["Quiz.EssaySolutionPlaceholder"] = "Write a solution sentence with the correct unit or subject (required)",
            ["Quiz.EssayCombinedLabel"] = "Solution, calculation, and answer",
            ["Quiz.EssayCombinedNumericLabel"] = "Calculation and answer",
            ["Quiz.EssayCombinedPlaceholder"] = "Write the solution sentence, then put the calculation and answer on new lines.",
            ["Quiz.EssayCombinedAnswerPlaceholder"] = "Answer: …",
            ["Quiz.EssayCombinedAnswerHint"] = "Write everything in the box above. Put the final answer on the last line as \"Answer: …\".",
            ["Quiz.EssayEquationLabel"] = "Calculation",
            ["Quiz.EssayEquationPlaceholder"] = "Example: 5 × 6 = 30",
            ["Quiz.AverageEssayEquationPlaceholder"] = "Example: (2 + 4 + 6 + 8) ÷ 4 = 5",
            ["Quiz.PercentageRatioEssayEquationPlaceholder"] = "Example: 20 ÷ 80 × 100 = 25",
            ["Quiz.PercentageValueEssayEquationPlaceholder"] = "Example: 200 × 25 ÷ 100 = 50",
            ["Quiz.PercentageWholeEssayEquationPlaceholder"] = "Example: 50 × 100 ÷ 25 = 200",
            ["Quiz.GeometryEssayEquationPlaceholder"] = "Example: (12 + 8) × 2 = 40",
            ["Quiz.EssayAnswerLabel"] = "Answer",
            ["Quiz.EssayAnswerPlaceholder"] = "Example: 30 pencils",
            ["Quiz.EssayValidationHint"] = "A solution sentence with the correct unit or subject is required. The app still checks the calculation, result, and answer unit.",
            ["Quiz.EssayValidationHintAlgorithm"] = "The app checks the two given numbers, operation, result, and final answer value.",
            ["Quiz.EssayValidationHintAlgorithmWordProblem"] = "A solution sentence needs the correct unit or subject (for example, kilograms, grams, money, eggs, or products). The calculation and final answer are still checked.",
            ["Quiz.EssayEquationUnitHint"] = "Write the correct unit immediately after the result in the calculation.",
            ["Quiz.GeometryEssayValidationHint"] = "A solution sentence with the correct unit or geometric object is required. The app checks the substituted formula, result, and unit power.",
            ["Quiz.SubmitEssayAnswer"] = "📝 Check answer",
            ["Quiz.EssayCorrectFeedback"] = "Correct! The solution sentence, calculation, and final answer are all right.",
            ["Quiz.EssayCorrectFeedbackNumeric"] = "Correct! The calculation and final answer are both right.",
            ["Quiz.EssaySolutionRequired"] = "The solution sentence is missing. It is required for a word problem.",
            ["Quiz.EssaySolutionContentIncorrect"] = "The solution sentence does not name the correct unit or subject from the problem.",
            ["Quiz.EssayEquationAndAnswerIncorrect"] = "The calculation and final answer are both incorrect.",
            ["Quiz.EssayEquationFormatIncorrect"] = "The calculation format is incomplete. Enter a full equation such as 5 × 6 = 30.",
            ["Quiz.EssayEquationIncorrect"] = "The calculation does not match the given numbers, operation, or result.",
            ["Quiz.EssayEquationUnitIncorrect"] = "The calculation result is missing a unit or uses the wrong unit.",
            ["Quiz.EssayAnswerIncorrect"] = "The calculation is correct, but the final answer is incorrect.",
            ["Quiz.EssayAnswerUnitIncorrect"] = "The answer value is correct, but its unit does not match the problem.",
            ["Quiz.RegenerateQuestion"] = "🔄 Generate again",
            ["Quiz.OperationTitle"] = "4. Choose a problem type",
            ["Quiz.OperationTitleAlgorithmOnly"] = "3. Choose a problem type",
            ["Quiz.OperationMixed"] = "Mixed",
            ["Quiz.ProblemBasic"] = "Basic + − × ÷",
            ["Quiz.ProblemFraction"] = "Fractions ½",
            ["Quiz.ProblemExpression"] = "Evaluate an expression",
            ["Quiz.ExpressionTypeTitle"] = "Choose an expression type",
            ["Quiz.ExpressionInteger"] = "Integers – Without brackets",
            ["Quiz.ExpressionIntegerBrackets"] = "Integers – With brackets",
            ["Quiz.ExpressionFraction"] = "Fractions – Without brackets",
            ["Quiz.ExpressionFractionBrackets"] = "Fractions – With brackets",
            ["Quiz.ExpressionDifficultyHint"] = "1–5 stars: 3–7 operands. Bracketed expressions have 1–5 bracket pairs respectively; each fraction counts as one operand.",
            ["Quiz.ExpressionQuestionTitle"] = "Evaluate the expression",
            ["Quiz.ExpressionEssayHint"] = "Enter the expression and its result after =, then the answer. No solution sentence or unit is needed. Equivalent fractions are accepted.",
            ["Quiz.AverageIndirectEssayHint"] = "Use one combined calculation or 2–3 steps. Put each equation with = on its own line; previous results may be reused. Separate solution sentences and units are optional for intermediate steps. Include the correct unit in the final calculation and answer.",
            ["Quiz.ExpressionIntegerPlaceholder"] = "Example: 1 + 2 + 3 = 6",
            ["Quiz.ExpressionFractionPlaceholder"] = "Example: (1/2 + 1/3) × 3/5 = 1/2",
            ["Quiz.ExpressionAnswerPlaceholder"] = "Example: 6",
            ["Quiz.BasicOperationTitle"] = "Choose a basic operation",
            ["Quiz.FractionOperationTitle"] = "Choose a fraction operation",
            ["Quiz.ProblemGeometry"] = "Geometry △ □ ◯",
            ["Quiz.GeometryMeasurementTitle"] = "Choose what to calculate",
            ["Quiz.GeometryPerimeter"] = "Perimeter",
            ["Quiz.GeometryArea"] = "Area",
            ["Quiz.GeometryVolume"] = "Volume",
            ["Quiz.GeometryLateralArea"] = "Lateral surface area",
            ["Quiz.GeometryTotalArea"] = "Total surface area",
            ["Quiz.ProblemFindX"] = "Find 𝑥",
            ["Quiz.ProblemProportion"] = "Direct / inverse proportion ↗↘",
            ["Quiz.ProblemMotion"] = "Motion ➜⏱️",
            ["Quiz.MotionQuestionTitle"] = "Motion problem",
            ["Quiz.MotionTypeTitle"] = "Choose a motion type",
            ["Quiz.MotionBasic"] = "Basic – One moving object",
            ["Quiz.MotionChasing"] = "Two objects in the same direction (catch-up)",
            ["Quiz.MotionMeeting"] = "Two objects in opposite directions (meeting)",
            ["Quiz.MotionRiver"] = "River motion (downstream / upstream)",
            ["Quiz.MotionEssayValidationHint"] = "A solution sentence with the correct unit or subject is required. The calculation must match the motion facts, and the answer needs the correct unit.",
            ["Quiz.MotionEssayEquationPlaceholder"] = "Example: 120 ÷ (60 + 40) = 1",
            ["Quiz.ProportionTypeTitle"] = "Choose a proportion type",
            ["Quiz.ProportionDirect"] = "↗ Direct proportion",
            ["Quiz.ProportionInverse"] = "↘ Inverse proportion",
            ["Quiz.ProportionQuestionTitle"] = "Direct / inverse proportion problem",
            ["Quiz.ProportionEssayValidationHint"] = "A solution sentence with the correct unit or subject is required. The app checks the proportion facts, calculation, and answer.",
            ["Quiz.ProportionEssayEquationPlaceholder"] = "Example: 24 ÷ 4 × 6 = 36",
            ["Quiz.FractionQuestionTitle"] = "Fraction problem",
            ["Quiz.FractionEssayEquationPlaceholder"] = "Example: 1/2 + 1/4 = 3/4",
            ["Quiz.FractionEssayValidationHint"] = "The app checks both fractions, the operation, and the reduced result.",
            ["Quiz.FractionEssayAnswerPlaceholder"] = "Example: 3/4 metre of fabric",
            ["Quiz.FindXQuestionTitle"] = "Find the value of 𝑥",
            ["Quiz.FindXEssayValidationHint"] = "The app checks the inverse calculation and 𝑥 value; a solution sentence is not needed for a numeric equation.",
            ["Quiz.FindXEssayEquationPlaceholder"] = "Example: 12 − 5 = 7",
            ["Quiz.WordProblemTitle"] = "Word problem",
            ["Quiz.PresentedAnswer"] = "Answer: {0} {1}",
            ["Quiz.SolutionTitle"] = "Solution"
        };

    public static bool TryGetValue(
        string key,
        string culture,
        out string value)
    {
        IReadOnlyDictionary<string, string> strings =
            culture.StartsWith(
                "vi",
                StringComparison.OrdinalIgnoreCase)
                ? Vietnamese
                : English;

        if (strings.TryGetValue(key, out value!)) return true;
        if (key == "Quiz.ProblemNumberSense" || key.StartsWith("Quiz.Elementary.", StringComparison.Ordinal)
            && Enum.TryParse<MathSolver.Models.ElementaryQuizType>(key[16..], out var type)
            && MathSolver.Services.ElementaryQuizGenerator.IsFoundationSkill(type))
        {
            value = MathSolver.Services.QuizContentCatalog.Text(culture.StartsWith("vi", StringComparison.OrdinalIgnoreCase) ? "vi-VN" : "en-US", key);
            return true;
        }
        return false;
    }
}
