namespace MathSolver.Services.Localization;

/// <summary>
/// Stable strings for the optional local-LLM quiz surface. Keeping these
/// isolated prevents an older imported language pack from replacing new AI
/// controls with raw [Quiz.*] keys. Non-Vietnamese cultures use English as the
/// safe fallback until a custom pack adds its own translations.
/// </summary>
internal static class QuizLocalizationOverrides
{
    private static readonly IReadOnlyDictionary<string, string> Vietnamese =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Quiz.PracticeSubtitle"] = "Thuật toán • Giáo viên AI • Đúng/Sai • 4 đáp án • Tự luận",
            ["Quiz.SourceTitle"] = "1. Chọn cách tạo đề",
            ["Quiz.AlgorithmSource"] = "🧮 Thuật toán",
            ["Quiz.LocalLlmSource"] = "🤖 AI / LLM",
            ["Quiz.ModeTitle"] = "2. Chọn kiểu câu hỏi",
            ["Quiz.EssayMode"] = "✍️ Tự luận",
            ["Quiz.EssayQuestionTitle"] = "Trình bày bài giải",
            ["Quiz.EssaySolutionLabel"] = "Lời giải",
            ["Quiz.EssaySolutionPlaceholder"] = "Viết câu lời giải nêu đúng đại lượng cần tìm (bắt buộc)",
            ["Quiz.EssayEquationLabel"] = "Phép tính",
            ["Quiz.EssayEquationPlaceholder"] = "Ví dụ: 5 × 6 = 30",
            ["Quiz.GeometryEssayEquationPlaceholder"] = "Ví dụ: (12 + 8) × 2 = 40",
            ["Quiz.EssayAnswerLabel"] = "Đáp số",
            ["Quiz.EssayAnswerPlaceholder"] = "Ví dụ: 30 cây bút",
            ["Quiz.EssayValidationHint"] = "Bắt buộc điền lời giải. Ứng dụng chấm đại lượng trong lời giải, phép tính, kết quả, giá trị và đơn vị đáp số.",
            ["Quiz.EssayValidationHintAlgorithm"] = "Ứng dụng chấm hai số dữ kiện, phép toán, kết quả và giá trị đáp số.",
            ["Quiz.GeometryEssayValidationHint"] = "Ứng dụng chấm công thức thay số, kết quả và đúng bậc đơn vị: độ dài, diện tích hoặc thể tích.",
            ["Quiz.GeometryEssayValidationHintAi"] = "Bắt buộc điền lời giải. Ứng dụng chấm đại lượng hình học, công thức thay số, kết quả và đúng bậc đơn vị.",
            ["Quiz.SubmitEssayAnswer"] = "📝 Chấm bài",
            ["Quiz.EssayCorrectFeedback"] = "Chính xác! Lời giải, phép tính và đáp số đều đúng.",
            ["Quiz.EssaySolutionRequired"] = "Em chưa điền lời giải. Phần lời giải là bắt buộc đối với bài toán đố.",
            ["Quiz.EssaySolutionContentIncorrect"] = "Lời giải chưa nêu đúng đại lượng cần tìm. Hãy dùng đúng tên đơn vị trong đề bài.",
            ["Quiz.EssayEquationAndAnswerIncorrect"] = "Phép tính và đáp số đều chưa đúng.",
            ["Quiz.EssayEquationFormatIncorrect"] = "Phép tính chưa đúng định dạng. Hãy nhập đầy đủ như 5 × 6 = 30.",
            ["Quiz.EssayEquationIncorrect"] = "Phép tính chưa đúng dữ kiện, phép toán hoặc kết quả.",
            ["Quiz.EssayAnswerIncorrect"] = "Phép tính đúng nhưng đáp số chưa đúng.",
            ["Quiz.EssayAnswerUnitIncorrect"] = "Giá trị đáp số đúng nhưng đơn vị chưa phù hợp với đề bài.",
            ["Quiz.RegenerateQuestion"] = "🔄 Tạo đề lại",
            ["Quiz.OperationTitle"] = "3. Chọn bài toán",
            ["Quiz.OperationMixed"] = "Hỗn hợp",
            ["Quiz.ProblemBasic"] = "Cơ bản + − × ÷",
            ["Quiz.ProblemFraction"] = "Phân số ½",
            ["Quiz.BasicOperationTitle"] = "Chọn phép tính cơ bản",
            ["Quiz.FractionOperationTitle"] = "Chọn phép tính phân số",
            ["Quiz.ProblemGeometry"] = "Hình học △ □ ◯",
            ["Quiz.ProblemFindX"] = "Tìm x",
            ["Quiz.ProblemProportion"] = "Tỉ lệ thuận / nghịch ↗↘",
            ["Quiz.ProblemMotion"] = "Chuyển động ➜⏱️",
            ["Quiz.MotionQuestionTitle"] = "Bài toán chuyển động",
            ["Quiz.MotionEssayValidationHint"] = "Nhập phép tính đúng theo dữ kiện chuyển động và đáp số kèm đúng đơn vị.",
            ["Quiz.MotionEssayValidationHintAi"] = "Bắt buộc điền lời giải, phép tính và đáp số. Phép tính phải đúng quan hệ chuyển động; đáp số phải kèm đúng đơn vị.",
            ["Quiz.MotionEssayEquationPlaceholder"] = "Ví dụ: 120 ÷ (60 + 40) = 1",
            ["Quiz.ProportionTypeTitle"] = "Chọn dạng tỉ lệ",
            ["Quiz.ProportionDirect"] = "↗ Tỉ lệ thuận",
            ["Quiz.ProportionInverse"] = "↘ Tỉ lệ nghịch",
            ["Quiz.ProportionQuestionTitle"] = "Bài toán tỉ lệ thuận / nghịch",
            ["Quiz.ProportionEssayValidationHint"] = "Ứng dụng chấm đúng dữ kiện tỉ lệ, công thức tính và giá trị đáp số.",
            ["Quiz.ProportionEssayValidationHintAi"] = "Bắt buộc điền lời giải. Ứng dụng chấm đúng quan hệ tỉ lệ, phép tính, kết quả và đơn vị đáp số.",
            ["Quiz.ProportionEssayEquationPlaceholder"] = "Ví dụ: 24 ÷ 4 × 6 = 36",
            ["Quiz.FractionQuestionTitle"] = "Bài toán phân số",
            ["Quiz.FractionEssayEquationPlaceholder"] = "Ví dụ: 1/2 + 1/4 = 3/4",
            ["Quiz.FractionEssayValidationHint"] = "Ứng dụng chấm hai phân số, phép tính và kết quả đã rút gọn.",
            ["Quiz.FractionEssayValidationHintAi"] = "Bắt buộc điền lời giải. Ứng dụng chấm hai phân số, phép tính, kết quả đã rút gọn và đúng đơn vị đáp số.",
            ["Quiz.FractionEssayAnswerPlaceholder"] = "Ví dụ: 3/4 mét vải",
            ["Quiz.FindXQuestionTitle"] = "Tìm giá trị của x",
            ["Quiz.FindXEssayValidationHint"] = "Ứng dụng chấm phép tính ngược và giá trị x; với đề AI, ứng dụng còn kiểm tra đúng đơn vị của x.",
            ["Quiz.FindXEssayValidationHintAi"] = "Bắt buộc điền lời giải. Ứng dụng chấm đúng đại lượng của x, phép tính ngược, giá trị và đơn vị của x.",
            ["Quiz.FindXEssayEquationPlaceholder"] = "Ví dụ: 12 − 5 = 7",
            ["Quiz.LlmSettingsTitle"] = "Giáo viên AI cục bộ",
            ["Quiz.LlmSettingsDescription"] = "AI viết đề theo chương trình tiểu học Việt Nam. Ứng dụng tự tính đáp án và kiểm tra lại trước khi hiển thị.",
            ["Quiz.DownloadGemma4"] = "⬇️ Tải model AI từ HuggingFace",
            ["Quiz.StopModelDownload"] = "⏹️ Dừng tải model",
            ["Quiz.ChooseDownloadModelTitle"] = "Chọn model Gemma",
            ["Quiz.DownloadE2BOption"] = "E2B • Nhẹ hơn • 3,35 GB",
            ["Quiz.DownloadE4BOption"] = "E4B • Chất lượng tốt hơn • 5,15 GB",
            ["Quiz.OpenModelWebsiteOption"] = "Mở trang {0} trên Hugging Face",
            ["Quiz.OpenModelWebsiteFailed"] = "Không thể mở trang model trên Hugging Face.",
            ["Quiz.ModelCatalogTitle"] = "Thư viện model Gemma",
            ["Quiz.ModelCatalogSubtitle"] = "Chọn model để xem chi tiết. Tất cả model trong thư viện đều tải trực tiếp trong ứng dụng; nút ↗ phía trên mở trang model đã chọn trên Hugging Face.",
            ["Quiz.ModelCatalogModelsHeading"] = "MODEL PHÙ HỢP",
            ["Quiz.ModelCatalogReadmeHeading"] = "CHI TIẾT",
            ["Quiz.ModelCatalogGuideTitle"] = "Chọn model phù hợp thiết bị",
            ["Quiz.ModelCatalogGuideBody"] = "Gemma 3 1B là lựa chọn siêu nhẹ; Gemma 4 E2B/E4B ưu tiên chất lượng cao hơn. Danh sách bên trái có thể cuộn để chọn model.",
            ["Quiz.ModelCatalogGemma3Title"] = "Gemma 3 1B • Siêu nhẹ",
            ["Quiz.ModelCatalogGemma3Description"] = "Khoảng 1,07 GB • Q8_0 • LM Studio Community",
            ["Quiz.ModelCatalogE2BTitle"] = "Gemma 4 E2B • Nhẹ hơn",
            ["Quiz.ModelCatalogE2BDescription"] = "Nhanh, ít RAM và tiết kiệm pin",
            ["Quiz.ModelCatalogE4BTitle"] = "Gemma 4 E4B • Chất lượng tốt hơn",
            ["Quiz.ModelCatalogE4BDescription"] = "Viết tự nhiên và suy luận tốt hơn",
            ["Quiz.ModelCatalogInteractionHint"] = "Bấm vào một model để xem chi tiết. Nút Tải sẽ mở thêm bước xác nhận đường dẫn lưu model.",
            ["Quiz.ModelCatalogMathSolverHeading"] = "Sử dụng trong Math Solver",
            ["Quiz.ModelCatalogMathSolverBody"] = "Model chỉ đảm nhiệm việc viết đề bài bằng ngôn ngữ tự nhiên. Dữ kiện, phép tính và đáp án vẫn được C# kiểm tra trước khi hiển thị; model chạy cục bộ và không gửi nội dung bài toán lên máy chủ.",
            ["Quiz.ModelCatalogRecommendationHeading"] = "Khuyến nghị",
            ["Quiz.ModelCatalogGemma3Summary"] = "Gemma 3 1B Instruct là model Gemma 3 nhỏ nhất. Math Solver dùng bản GGUF Q8_0 khoảng 1,07 GB do LM Studio Community phát hành và được bartowski quantize bằng llama.cpp. Q8_0 giữ độ chính xác của weights tốt hơn Q4, nên Math Solver ưu tiên bản này để giảm nguy cơ lặp token, text rác/gibberish đã gặp khi thử các bản Q4.",
            ["Quiz.ModelCatalogGemma3MathSolverBody"] = "Gemma 3 1B Q8_0 dùng với LLamaSharp trên Windows. Nút Tải dùng cùng luồng tải trực tiếp trong ứng dụng như Gemma 4: chọn thư mục lưu, theo dõi tiến trình và tiếp tục phần tải dở nếu bị gián đoạn. Nút ↗ phía trên mở trang LM Studio Community trên Hugging Face để xem model card và giấy phép.",
            ["Quiz.ModelCatalogGemma3Recommendation"] = "Khuyến nghị khi cần model 1B nhẹ nhưng ưu tiên độ ổn định đầu ra hơn dung lượng tối thiểu. Q8_0 lớn hơn và có thể chậm hơn Q4 một chút, đổi lại giảm sai số lượng tử. Model vẫn chỉ có 1B tham số nên validator C# tiếp tục là lớp kiểm tra bắt buộc trước khi hiển thị đề.",
            ["Quiz.ModelCatalogGemma3FileBody"] = "{0}\nKhoảng {1} GB • GGUF • Q8_0\nNguồn: LM Studio Community trên Hugging Face • quantized by bartowski • giấy phép Gemma",
            ["Quiz.ModelCatalogE2BSummary"] = "Gemma 4 E2B Instruct là biến thể nhỏ hướng tới thiết bị cá nhân. Bản GGUF QAT Q4_0 giảm bộ nhớ cần thiết trong khi giữ chất lượng gần với checkpoint độ chính xác cao hơn.",
            ["Quiz.ModelCatalogE4BSummary"] = "Gemma 4 E4B Instruct có năng lực ngôn ngữ và suy luận tốt hơn E2B. Bản GGUF QAT Q4_0 phù hợp khi ưu tiên đề bài tự nhiên và đa dạng hơn.",
            ["Quiz.ModelCatalogE2BRecommendation"] = "Nên chọn cho điện thoại, máy ít RAM hoặc khi ưu tiên tốc độ, nhiệt độ và thời lượng pin. Đây là lựa chọn mặc định hợp lý để tạo toán đố tiểu học.",
            ["Quiz.ModelCatalogE4BRecommendation"] = "Nên chọn cho PC hoặc thiết bị có nhiều RAM khi ưu tiên chất lượng câu chữ. Model tải và chạy nặng hơn E2B nhưng thường tạo đề tự nhiên hơn.",
            ["Quiz.ModelCatalogFileHeading"] = "Thông tin bản tải",
            ["Quiz.ModelCatalogFileBody"] = "{0}\nKhoảng {1} GB • GGUF • QAT Q4_0\nNguồn: Google DeepMind trên Hugging Face • Apache 2.0",
            ["Quiz.ModelCatalogOpenPage"] = "Mở trang {0} trên Hugging Face",
            ["Quiz.ModelCatalogDownloadModel"] = "Tải {0}",
            ["Quiz.ModelCatalogOpenFailedTitle"] = "Không thể mở trang",
            ["Quiz.ModelCatalogClose"] = "Đóng",
            ["Quiz.ModelCatalogFooterHint"] = "Cuộn danh sách bên trái để chọn model. Gemma 4 tải trực tiếp trong ứng dụng; Gemma 3 1B Q8_0 dùng nút Tải để mở file của LM Studio Community trên Hugging Face vì kho có thể yêu cầu đăng nhập/chấp nhận giấy phép Gemma.",
            ["Quiz.OpenActionShort"] = "↗ Mở",
            ["Quiz.DownloadActionShort"] = "↓ Tải",
            ["Quiz.DownloadPathPopupTitle"] = "Xác nhận nơi lưu model",
            ["Quiz.DownloadPathPopupSubtitle"] = "Bạn có thể giữ đường dẫn mặc định hoặc chọn một thư mục khác trước khi tải.",
            ["Quiz.DownloadPathPopupModelHeading"] = "Model đã chọn",
            ["Quiz.DownloadPathPopupModelMeta"] = "Khoảng {0} GB • {1}",
            ["Quiz.DownloadPathPopupPathHeading"] = "Thư mục lưu model",
            ["Quiz.DownloadPathPopupChooseFolder"] = "📁 Chọn thư mục",
            ["Quiz.DownloadPathPopupResetDefault"] = "Mặc định",
            ["Quiz.DownloadPathPopupFinalFileHeading"] = "File GGUF sẽ lưu tại",
            ["Quiz.DownloadPathPopupFolderPickerFailedTitle"] = "Không mở được trình chọn thư mục",
            ["Quiz.DownloadPathPopupFolderPickerFailedMessage"] = "Không thể mở hoặc đọc thư mục đã chọn. Hãy thử chọn một thư mục khác.",
            ["Quiz.DownloadPathPopupFolderNotWritableTitle"] = "Không thể lưu vào thư mục này",
            ["Quiz.DownloadPathPopupFolderNotWritableMessage"] = "Math Solver không có quyền ghi file vào thư mục đã chọn. Hãy chọn một thư mục khác có quyền ghi.",
            ["Quiz.DownloadPathPopupNote"] = "Hãy bảo đảm ổ đĩa còn đủ dung lượng trống. Nếu tải bị gián đoạn, phần đã tải sẽ được giữ lại trong chính thư mục bạn chọn để tiếp tục lần sau.",
            ["Quiz.Cancel"] = "Hủy",
            ["Quiz.DownloadConfirmTitle"] = "Xác nhận tải model",
            ["Quiz.DownloadConfirmMessage"] = "Tải {0} (khoảng {1} GB) từ Hugging Face? Nên dùng Wi-Fi và bảo đảm thiết bị còn đủ dung lượng trống.",
            ["Quiz.DownloadAction"] = "Tải xuống",
            ["Quiz.DownloadingModel"] = "Đang bắt đầu tải {0}...",
            ["Quiz.DownloadingModelProgress"] = "Đang tải {0}: {1}% • {2}/{3} GB",
            ["Quiz.DownloadComplete"] = "Đã tải và chọn {0}. File GGUF đã sẵn sàng.",
            ["Quiz.DownloadCancelled"] = "Đã dừng tải. Phần đã tải được giữ lại để tiếp tục lần sau.",
            ["Quiz.DownloadInvalid"] = "File tải về không phải model Gemma GGUF được hỗ trợ. Hãy thử tải lại.",
            ["Quiz.DownloadAccessDenied"] = "Hugging Face không cho phép tải model này. Hãy kiểm tra kết nối hoặc quyền truy cập rồi thử lại.",
            ["Quiz.DownloadFailed"] = "Không thể tải model. Hãy kiểm tra kết nối mạng; lần tải sau sẽ tiếp tục từ phần đã có.",
            ["Quiz.SelectModel"] = "📦 Chọn model",
            ["Quiz.EjectModel"] = "⏏️ Eject model",
            ["Quiz.OpenInFileExplorer"] = "📂 Mở trong File Explorer",
            ["Quiz.ModelLocationTitle"] = "Vị trí AI model",
            ["Quiz.ModelLocationUnavailable"] = "Nền tảng này không cho phép mở trực tiếp thư mục riêng của ứng dụng. AI model đang nằm tại:\n{0}",
            ["Quiz.NoModelSelected"] = "Chưa chọn model GGUF",
            ["Quiz.ModelRecommendation"] = "Ứng dụng hỗ trợ Gemma 3 1B và Gemma 4 E2B/E4B dạng GGUF. Gemma 3 1B nhẹ nhất; Gemma 4 phù hợp hơn khi ưu tiên chất lượng câu chữ.",
            ["Quiz.RecommendedModelDetected"] = "Model Gemma đã sẵn sàng để tạo đề.",
            ["Quiz.CreateWithAi"] = "✨ Tạo đề bằng AI",
            ["Quiz.StopAiGeneration"] = "⏹️ Dừng tạo đề",
            ["Quiz.ShowAiDiagnostics"] = "Hiện JSON & Log",
            ["Quiz.HideAiDiagnostics"] = "Ẩn JSON & Log",
            ["Quiz.AiDiagnosticsTitle"] = "JSON và log kiểm tra AI",
            ["Quiz.AiDiagnosticsDescription"] = "Xem dữ liệu model trả về và từng bước validation của C#.",
            ["Quiz.AiValidationCheckingTitle"] = "Đang kiểm tra đề AI",
            ["Quiz.AiValidationCheckingDetail"] = "C# đang parse và validation đề ở lần {0}/{1}.",
            ["Quiz.AiValidationValidTitle"] = "Đề AI hợp lệ",
            ["Quiz.AiValidationValidDetail"] = "Validation thành công ở lần {0}/{1}. Dữ kiện, đơn vị và quan hệ toán đã được C# chấp nhận.",
            ["Quiz.AiValidationInvalidTitle"] = "Đề AI chưa hợp lệ",
            ["Quiz.AiValidationInvalidFallback"] = "Đề không vượt qua validation. Model cần tạo lại câu khác.",
            ["Quiz.AiValidationRetryTitle"] = "Đề chưa hợp lệ — đang tạo lại",
            ["Quiz.AiValidationGenerationFailedTitle"] = "Không tạo được đề hợp lệ",
            ["Quiz.AiValidationRuntimeErrorTitle"] = "Validation bị gián đoạn",
            ["Quiz.AiValidationRuntimeErrorFallback"] = "Có lỗi runtime khi tạo hoặc kiểm tra đề AI.",
            ["Quiz.RawJsonTitle"] = "JSON do LLM tạo",
            ["Quiz.ValidationLogTitle"] = "Log validation",
            ["Quiz.DiagnosticsNoJson"] = "JSON thô sẽ xuất hiện tại đây khi AI bắt đầu tạo đề.",
            ["Quiz.DiagnosticsNoLog"] = "Log parse và validation sẽ xuất hiện tại đây.",
            ["Quiz.DiagnosticsAttemptHeader"] = "── Lần {0}/{1} ──",
            ["Quiz.DiagnosticsAttemptStarted"] = "[{0}/{1}] Bắt đầu nhận JSON từ model.",
            ["Quiz.DiagnosticsJsonReceived"] = "[{0}/{1}] Đã nhận {2} ký tự; bắt đầu parse JSON.",
            ["Quiz.DiagnosticsParseSucceeded"] = "[{0}/{1}] Parse JSON thành công.",
            ["Quiz.DiagnosticsParseFailed"] = "[{0}/{1}] Parse JSON thất bại: {2}.",
            ["Quiz.DiagnosticsValidationSucceeded"] = "[{0}/{1}] Validation thành công; đề được chấp nhận.",
            ["Quiz.DiagnosticsValidationFailed"] = "[{0}/{1}] Validation từ chối đề: {2}.",
            ["Quiz.DiagnosticsRetryScheduled"] = "[{0}/{1}] Tạo lại đề do lỗi: {2}.",
            ["Quiz.DiagnosticsGenerationFailed"] = "[{0}/{1}] Đã hết số lần thử; lỗi cuối: {2}.",
            ["Quiz.DiagnosticsRuntimeError"] = "[{0}/{1}] Lỗi runtime AI: {2}.",
            ["Quiz.SelectModelPickerTitle"] = "Chọn file Gemma GGUF",
            ["Quiz.ImportingModel"] = "Đang kiểm tra file Gemma...",
            ["Quiz.ModelReady"] = "File model GGUF đúng định dạng.",
            ["Quiz.ModelEjected"] = "Đã Eject model và đặt lại toàn bộ phiên luyện tập.",
            ["Quiz.UnsupportedModelFamily"] = "Chỉ hỗ trợ Gemma 3 hoặc Gemma 4 dành cho tạo đề. Hãy chọn đúng file GGUF tương thích.",
            ["Quiz.ModelTooLarge"] = "Model này quá nặng (trên 5,5 GB) nên có thể làm máy nóng và hao pin. Hãy chọn Gemma 4 E2B/E4B bản Q4 nhỏ hơn.",
            ["Quiz.InvalidModelFile"] = "File đã chọn không phải là file GGUF hợp lệ.",
            ["Quiz.ModelImportError"] = "Không thể mở hoặc lưu model đã chọn.",
            ["Quiz.SelectModelFirst"] = "Hãy chọn model GGUF trước khi tạo đề bằng AI.",
            ["Quiz.LlmReady"] = "Chọn bài toán rồi bấm Tạo đề bằng AI.",
            ["Quiz.AiTeacherGreetingTitle"] = "Giáo viên AI",
            ["Quiz.AiTeacherStateNoModel"] = "Chưa có model",
            ["Quiz.AiTeacherStateModelSelected"] = "Đã chọn model",
            ["Quiz.AiTeacherStateWorking"] = "Đang làm việc",
            ["Quiz.AiTeacherStateReady"] = "Sẵn sàng",
            ["Quiz.FirstModelGreeting"] = "Chào em! Giáo viên AI đã sẵn sàng. Chúng ta cùng bắt đầu bài toán đầu tiên nhé!",
            ["Quiz.LoadingModel"] = "Đang tạo sinh đề bài bằng AI...",
            ["Quiz.ModelLoaded"] = "AI đang chuẩn bị nội dung câu hỏi...",
            ["Quiz.GeneratingAttempt"] = "AI đang viết đề bài, lần {0}/{1}...",
            ["Quiz.GenerationSpeed"] = "Tốc độ tạo sinh: {0} token/s",
            ["Quiz.ValidatingProblem"] = "Đang kiểm tra lại đề bài và đáp án...",
            ["Quiz.RetryingProblem"] = "Đề chưa hợp lệ. AI đang tự tạo lại...",
            ["Quiz.DisposingModel"] = "Đang Eject model...",
            ["Quiz.GenerationSucceeded"] = "Đề bài đã sẵn sàng.",
            ["Quiz.GenerationCancelled"] = "Đã dừng tạo đề.",
            ["Quiz.GenerationFailedAfterRetries"] = "AI đã tạo sai dữ kiện 3 lần. Hãy bấm Tạo đề bằng AI để thử lại.",
            ["Quiz.NotEnoughMemory"] = "Model này quá nặng đối với thiết bị. Hãy chọn Gemma 4 E2B/E4B bản Q4 nhỏ hơn.",
            ["Quiz.ModelRuntimeError"] = "Không thể dùng model này trên thiết bị. Hãy chọn Gemma 4 E2B/E4B bản Q4 nhỏ hơn.",
            ["Quiz.WordProblemTitle"] = "Bài toán do giáo viên AI tạo",
            ["Quiz.PresentedAnswer"] = "Đáp án được đưa ra: {0} {1}",
            ["Quiz.SolutionTitle"] = "Lời giải"
        };

    private static readonly IReadOnlyDictionary<string, string> English =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Quiz.PracticeSubtitle"] = "Algorithm • AI teacher • True/False • 4 choices • Written answer",
            ["Quiz.SourceTitle"] = "1. Choose how to create questions",
            ["Quiz.AlgorithmSource"] = "🧮 Algorithm",
            ["Quiz.LocalLlmSource"] = "🤖 AI / LLM",
            ["Quiz.ModeTitle"] = "2. Choose a question mode",
            ["Quiz.EssayMode"] = "✍️ Written",
            ["Quiz.EssayQuestionTitle"] = "Show your solution",
            ["Quiz.EssaySolutionLabel"] = "Solution sentence",
            ["Quiz.EssaySolutionPlaceholder"] = "Write a solution sentence naming the requested quantity (required)",
            ["Quiz.EssayEquationLabel"] = "Calculation",
            ["Quiz.EssayEquationPlaceholder"] = "Example: 5 × 6 = 30",
            ["Quiz.GeometryEssayEquationPlaceholder"] = "Example: (12 + 8) × 2 = 40",
            ["Quiz.EssayAnswerLabel"] = "Answer",
            ["Quiz.EssayAnswerPlaceholder"] = "Example: 30 pencils",
            ["Quiz.EssayValidationHint"] = "A solution sentence is required. The app checks its requested quantity, the calculation, result, answer value, and answer unit.",
            ["Quiz.EssayValidationHintAlgorithm"] = "The app checks the two given numbers, operation, result, and final answer value.",
            ["Quiz.GeometryEssayValidationHint"] = "The app checks the substituted formula, result, and the correct unit power for length, area, or volume.",
            ["Quiz.GeometryEssayValidationHintAi"] = "A solution sentence is required. The app checks the geometry quantity, substituted formula, result, and unit power.",
            ["Quiz.SubmitEssayAnswer"] = "📝 Check answer",
            ["Quiz.EssayCorrectFeedback"] = "Correct! The solution sentence, calculation, and final answer are all right.",
            ["Quiz.EssaySolutionRequired"] = "The solution sentence is missing. It is required for an AI word problem.",
            ["Quiz.EssaySolutionContentIncorrect"] = "The solution sentence does not name the requested quantity. Use the unit stated in the problem.",
            ["Quiz.EssayEquationAndAnswerIncorrect"] = "The calculation and final answer are both incorrect.",
            ["Quiz.EssayEquationFormatIncorrect"] = "The calculation format is incomplete. Enter a full equation such as 5 × 6 = 30.",
            ["Quiz.EssayEquationIncorrect"] = "The calculation does not match the given numbers, operation, or result.",
            ["Quiz.EssayAnswerIncorrect"] = "The calculation is correct, but the final answer is incorrect.",
            ["Quiz.EssayAnswerUnitIncorrect"] = "The answer value is correct, but its unit does not match the problem.",
            ["Quiz.RegenerateQuestion"] = "🔄 Generate again",
            ["Quiz.OperationTitle"] = "3. Choose a problem type",
            ["Quiz.OperationMixed"] = "Mixed",
            ["Quiz.ProblemBasic"] = "Basic + − × ÷",
            ["Quiz.ProblemFraction"] = "Fractions ½",
            ["Quiz.BasicOperationTitle"] = "Choose a basic operation",
            ["Quiz.FractionOperationTitle"] = "Choose a fraction operation",
            ["Quiz.ProblemGeometry"] = "Geometry △ □ ◯",
            ["Quiz.ProblemFindX"] = "Find x",
            ["Quiz.ProblemProportion"] = "Direct / inverse proportion ↗↘",
            ["Quiz.ProblemMotion"] = "Motion ➜⏱️",
            ["Quiz.MotionQuestionTitle"] = "Motion problem",
            ["Quiz.MotionEssayValidationHint"] = "Enter a calculation that matches the motion facts and an answer with the correct unit.",
            ["Quiz.MotionEssayValidationHintAi"] = "A written solution, calculation, and final answer are required. The calculation must preserve the motion relationship and the answer must include the correct unit.",
            ["Quiz.MotionEssayEquationPlaceholder"] = "Example: 120 ÷ (60 + 40) = 1",
            ["Quiz.ProportionTypeTitle"] = "Choose a proportion type",
            ["Quiz.ProportionDirect"] = "↗ Direct proportion",
            ["Quiz.ProportionInverse"] = "↘ Inverse proportion",
            ["Quiz.ProportionQuestionTitle"] = "Direct / inverse proportion problem",
            ["Quiz.ProportionEssayValidationHint"] = "The app checks the proportion facts, calculation, and final answer value.",
            ["Quiz.ProportionEssayValidationHintAi"] = "A solution sentence is required. The app checks the proportion relationship, calculation, result, and answer unit.",
            ["Quiz.ProportionEssayEquationPlaceholder"] = "Example: 24 ÷ 4 × 6 = 36",
            ["Quiz.FractionQuestionTitle"] = "Fraction problem",
            ["Quiz.FractionEssayEquationPlaceholder"] = "Example: 1/2 + 1/4 = 3/4",
            ["Quiz.FractionEssayValidationHint"] = "The app checks both fractions, the operation, and the reduced result.",
            ["Quiz.FractionEssayValidationHintAi"] = "A solution sentence is required. The app checks both fractions, the operation, reduced result, and answer unit.",
            ["Quiz.FractionEssayAnswerPlaceholder"] = "Example: 3/4 metre of fabric",
            ["Quiz.FindXQuestionTitle"] = "Find the value of x",
            ["Quiz.FindXEssayValidationHint"] = "The app checks the inverse calculation and x value; AI problems also require the correct unit for x.",
            ["Quiz.FindXEssayValidationHintAi"] = "A solution sentence is required. The app checks x's quantity, inverse calculation, value, and unit.",
            ["Quiz.FindXEssayEquationPlaceholder"] = "Example: 12 − 5 = 7",
            ["Quiz.LlmSettingsTitle"] = "Local AI teacher",
            ["Quiz.LlmSettingsDescription"] = "AI writes elementary math problems. The app calculates the answer and checks each problem before showing it.",
            ["Quiz.DownloadGemma4"] = "⬇️ Download AI model from HuggingFace",
            ["Quiz.StopModelDownload"] = "⏹️ Stop model download",
            ["Quiz.ChooseDownloadModelTitle"] = "Choose a Gemma model",
            ["Quiz.DownloadE2BOption"] = "E2B • Lighter • 3.35 GB",
            ["Quiz.DownloadE4BOption"] = "E4B • Better quality • 5.15 GB",
            ["Quiz.OpenModelWebsiteOption"] = "Open the {0} page on Hugging Face",
            ["Quiz.OpenModelWebsiteFailed"] = "The model page on Hugging Face could not be opened.",
            ["Quiz.ModelCatalogTitle"] = "Gemma model library",
            ["Quiz.ModelCatalogSubtitle"] = "Select a model to read its details. Every model in the library downloads directly inside the app; the ↗ button above opens the selected model page on Hugging Face.",
            ["Quiz.ModelCatalogModelsHeading"] = "BEST-FIT MODELS",
            ["Quiz.ModelCatalogReadmeHeading"] = "DETAILS",
            ["Quiz.ModelCatalogGuideTitle"] = "Pick the model that fits your device",
            ["Quiz.ModelCatalogGuideBody"] = "Gemma 3 1B is the ultra-light option; Gemma 4 E2B/E4B prioritize higher quality. Scroll the list on the left to choose a model.",
            ["Quiz.ModelCatalogGemma3Title"] = "Gemma 3 1B • Ultra-light",
            ["Quiz.ModelCatalogGemma3Description"] = "About 1.07 GB • Q8_0 • LM Studio Community",
            ["Quiz.ModelCatalogE2BTitle"] = "Gemma 4 E2B • Lighter",
            ["Quiz.ModelCatalogE2BDescription"] = "Fast, lower RAM use, and battery friendly",
            ["Quiz.ModelCatalogE4BTitle"] = "Gemma 4 E4B • Better quality",
            ["Quiz.ModelCatalogE4BDescription"] = "More natural writing and stronger reasoning",
            ["Quiz.ModelCatalogInteractionHint"] = "Select a model to inspect it. The Download button opens a final save-location confirmation step.",
            ["Quiz.ModelCatalogMathSolverHeading"] = "Use in Math Solver",
            ["Quiz.ModelCatalogMathSolverBody"] = "The model only writes the problem in natural language. C# still validates the facts, calculation, and answer before display; the model runs locally and does not send problem content to a server.",
            ["Quiz.ModelCatalogRecommendationHeading"] = "Recommendation",
            ["Quiz.ModelCatalogGemma3Summary"] = "Gemma 3 1B Instruct is the smallest Gemma 3 model. Math Solver uses the roughly 1.07 GB Q8_0 GGUF published by LM Studio Community and quantized by bartowski with llama.cpp. Q8_0 preserves weight precision better than Q4, so Math Solver prefers it to reduce the risk of token repetition and gibberish observed during testing with Q4 builds.",
            ["Quiz.ModelCatalogGemma3MathSolverBody"] = "Gemma 3 1B Q8_0 runs with LLamaSharp on Windows. Download now uses the same in-app transfer flow as Gemma 4: choose a save folder, track progress, and resume a partial transfer after interruption. The ↗ button above opens the LM Studio Community page on Hugging Face for the model card and license.",
            ["Quiz.ModelCatalogGemma3Recommendation"] = "Recommended when you want a lightweight 1B model but prioritize output stability over the smallest possible file. Q8_0 is larger and may decode a little slower than Q4, but it reduces quantization error. The model is still only 1B, so the C# validator remains mandatory before a generated problem is shown.",
            ["Quiz.ModelCatalogGemma3FileBody"] = "{0}\nAbout {1} GB • GGUF • Q8_0\nSource: LM Studio Community on Hugging Face • quantized by bartowski • Gemma license",
            ["Quiz.ModelCatalogE2BSummary"] = "Gemma 4 E2B Instruct is the smaller variant for personal devices. The QAT Q4_0 GGUF build reduces memory requirements while retaining quality close to a higher-precision checkpoint.",
            ["Quiz.ModelCatalogE4BSummary"] = "Gemma 4 E4B Instruct provides stronger language and reasoning quality than E2B. Its QAT Q4_0 GGUF build is suitable when more natural and varied problems are the priority.",
            ["Quiz.ModelCatalogE2BRecommendation"] = "Recommended for phones, lower-memory devices, or when speed, temperature, and battery life matter. It is a sensible default for elementary word problems.",
            ["Quiz.ModelCatalogE4BRecommendation"] = "Recommended for PCs or devices with more RAM when wording quality is the priority. It takes more storage and compute than E2B but usually produces more natural problems.",
            ["Quiz.ModelCatalogFileHeading"] = "Download information",
            ["Quiz.ModelCatalogFileBody"] = "{0}\nAbout {1} GB • GGUF • QAT Q4_0\nSource: Google DeepMind on Hugging Face • Apache 2.0",
            ["Quiz.ModelCatalogOpenPage"] = "Open the {0} page on Hugging Face",
            ["Quiz.ModelCatalogDownloadModel"] = "Download {0}",
            ["Quiz.ModelCatalogOpenFailedTitle"] = "Could not open page",
            ["Quiz.ModelCatalogClose"] = "Close",
            ["Quiz.ModelCatalogFooterHint"] = "Scroll the list on the left to choose a model. Gemma 4 downloads inside the app; Gemma 3 1B Q8_0 uses Download to open the LM Studio Community file on Hugging Face because the repository may require sign-in/acceptance of the Gemma license.",
            ["Quiz.OpenActionShort"] = "↗ Open",
            ["Quiz.DownloadActionShort"] = "↓ Download",
            ["Quiz.DownloadPathPopupTitle"] = "Confirm the save location",
            ["Quiz.DownloadPathPopupSubtitle"] = "Keep the default location or choose a different folder before the download starts.",
            ["Quiz.DownloadPathPopupModelHeading"] = "Selected model",
            ["Quiz.DownloadPathPopupModelMeta"] = "About {0} GB • {1}",
            ["Quiz.DownloadPathPopupPathHeading"] = "Model folder",
            ["Quiz.DownloadPathPopupChooseFolder"] = "📁 Choose folder",
            ["Quiz.DownloadPathPopupResetDefault"] = "Default",
            ["Quiz.DownloadPathPopupFinalFileHeading"] = "GGUF file will be saved to",
            ["Quiz.DownloadPathPopupFolderPickerFailedTitle"] = "Could not open the folder picker",
            ["Quiz.DownloadPathPopupFolderPickerFailedMessage"] = "The selected folder could not be opened or read. Try choosing a different folder.",
            ["Quiz.DownloadPathPopupFolderNotWritableTitle"] = "Cannot save to this folder",
            ["Quiz.DownloadPathPopupFolderNotWritableMessage"] = "Math Solver does not have permission to write files to the selected folder. Choose another writable folder.",
            ["Quiz.DownloadPathPopupNote"] = "Make sure the drive has enough free space. If the download is interrupted, the partial file stays in the folder you selected so it can resume next time.",
            ["Quiz.Cancel"] = "Cancel",
            ["Quiz.DownloadConfirmTitle"] = "Confirm model download",
            ["Quiz.DownloadConfirmMessage"] = "Download {0} (about {1} GB) from Hugging Face? Wi-Fi is recommended, and the device needs enough free storage.",
            ["Quiz.DownloadAction"] = "Download",
            ["Quiz.DownloadingModel"] = "Starting the {0} download...",
            ["Quiz.DownloadingModelProgress"] = "Downloading {0}: {1}% • {2}/{3} GB",
            ["Quiz.DownloadComplete"] = "{0} was downloaded and selected. The GGUF file is ready.",
            ["Quiz.DownloadCancelled"] = "Download stopped. The completed portion was kept so it can resume next time.",
            ["Quiz.DownloadInvalid"] = "The downloaded file is not a supported Gemma GGUF model. Try downloading it again.",
            ["Quiz.DownloadAccessDenied"] = "Hugging Face did not allow this model download. Check the connection or access permission, then try again.",
            ["Quiz.DownloadFailed"] = "The model could not be downloaded. Check the network connection; the next download will resume from the completed portion.",
            ["Quiz.SelectModel"] = "📦 Choose model",
            ["Quiz.EjectModel"] = "⏏️ Eject model",
            ["Quiz.OpenInFileExplorer"] = "📂 Open in File Explorer",
            ["Quiz.ModelLocationTitle"] = "AI model location",
            ["Quiz.ModelLocationUnavailable"] = "This platform cannot open the app's private folder directly. The AI model is stored at:\n{0}",
            ["Quiz.NoModelSelected"] = "No GGUF model selected",
            ["Quiz.ModelRecommendation"] = "The app supports Gemma 3 1B and Gemma 4 E2B/E4B GGUF models. Gemma 3 1B is the lightest option; Gemma 4 is preferable when wording quality matters more.",
            ["Quiz.RecommendedModelDetected"] = "A Gemma model is ready to create questions.",
            ["Quiz.CreateWithAi"] = "✨ Create with AI",
            ["Quiz.StopAiGeneration"] = "⏹️ Stop generation",
            ["Quiz.ShowAiDiagnostics"] = "Show JSON & Log",
            ["Quiz.HideAiDiagnostics"] = "Hide JSON & Log",
            ["Quiz.AiDiagnosticsTitle"] = "AI JSON and validation log",
            ["Quiz.AiDiagnosticsDescription"] = "Inspect the model output and each C# validation step.",
            ["Quiz.AiValidationCheckingTitle"] = "Checking the AI problem",
            ["Quiz.AiValidationCheckingDetail"] = "C# is parsing and validating attempt {0}/{1}.",
            ["Quiz.AiValidationValidTitle"] = "AI problem is valid",
            ["Quiz.AiValidationValidDetail"] = "Validation passed on attempt {0}/{1}. C# accepted the facts, units, and mathematical relationship.",
            ["Quiz.AiValidationInvalidTitle"] = "AI problem is not valid yet",
            ["Quiz.AiValidationInvalidFallback"] = "The problem did not pass validation and must be regenerated.",
            ["Quiz.AiValidationRetryTitle"] = "Problem rejected — generating again",
            ["Quiz.AiValidationGenerationFailedTitle"] = "No valid problem was generated",
            ["Quiz.AiValidationRuntimeErrorTitle"] = "Validation was interrupted",
            ["Quiz.AiValidationRuntimeErrorFallback"] = "A runtime error occurred while generating or validating the AI problem.",
            ["Quiz.RawJsonTitle"] = "JSON generated by the LLM",
            ["Quiz.ValidationLogTitle"] = "Validation log",
            ["Quiz.DiagnosticsNoJson"] = "Raw JSON will appear here when AI generation starts.",
            ["Quiz.DiagnosticsNoLog"] = "Parse and validation events will appear here.",
            ["Quiz.DiagnosticsAttemptHeader"] = "── Attempt {0}/{1} ──",
            ["Quiz.DiagnosticsAttemptStarted"] = "[{0}/{1}] Started receiving JSON from the model.",
            ["Quiz.DiagnosticsJsonReceived"] = "[{0}/{1}] Received {2} characters; parsing JSON.",
            ["Quiz.DiagnosticsParseSucceeded"] = "[{0}/{1}] JSON parsing succeeded.",
            ["Quiz.DiagnosticsParseFailed"] = "[{0}/{1}] JSON parsing failed: {2}.",
            ["Quiz.DiagnosticsValidationSucceeded"] = "[{0}/{1}] Validation succeeded; the problem was accepted.",
            ["Quiz.DiagnosticsValidationFailed"] = "[{0}/{1}] Validation rejected the problem: {2}.",
            ["Quiz.DiagnosticsRetryScheduled"] = "[{0}/{1}] Regenerating because of: {2}.",
            ["Quiz.DiagnosticsGenerationFailed"] = "[{0}/{1}] No attempts remain; final error: {2}.",
            ["Quiz.DiagnosticsRuntimeError"] = "[{0}/{1}] AI runtime error: {2}.",
            ["Quiz.SelectModelPickerTitle"] = "Choose a Gemma GGUF file",
            ["Quiz.ImportingModel"] = "Checking the Gemma file...",
            ["Quiz.ModelReady"] = "The GGUF model file is valid.",
            ["Quiz.ModelEjected"] = "The model was ejected and the practice session was reset.",
            ["Quiz.UnsupportedModelFamily"] = "Only Gemma 3 or Gemma 4 models are supported for question creation. Choose a compatible GGUF file.",
            ["Quiz.ModelTooLarge"] = "This model is too large (over 5.5 GB) and may heat the device or drain the battery. Choose a smaller Gemma 4 E2B/E4B Q4 model.",
            ["Quiz.InvalidModelFile"] = "The selected file is not a valid GGUF file.",
            ["Quiz.ModelImportError"] = "The selected model could not be opened or saved.",
            ["Quiz.SelectModelFirst"] = "Choose a GGUF model before creating a question with AI.",
            ["Quiz.LlmReady"] = "Choose a problem type, then select Create with AI.",
            ["Quiz.AiTeacherGreetingTitle"] = "AI teacher",
            ["Quiz.AiTeacherStateNoModel"] = "No model",
            ["Quiz.AiTeacherStateModelSelected"] = "Model selected",
            ["Quiz.AiTeacherStateWorking"] = "Working",
            ["Quiz.AiTeacherStateReady"] = "Ready",
            ["Quiz.FirstModelGreeting"] = "Hello! Your AI teacher is ready. Let’s begin the first math problem!",
            ["Quiz.LoadingModel"] = "Creating a math problem with AI...",
            ["Quiz.ModelLoaded"] = "AI is preparing the question...",
            ["Quiz.GeneratingAttempt"] = "AI is writing the problem, attempt {0}/{1}...",
            ["Quiz.GenerationSpeed"] = "Generation speed: {0} token/s",
            ["Quiz.ValidatingProblem"] = "Checking the problem and answer...",
            ["Quiz.RetryingProblem"] = "That problem was not valid. AI is trying again...",
            ["Quiz.DisposingModel"] = "Ejecting the model...",
            ["Quiz.GenerationSucceeded"] = "The problem is ready.",
            ["Quiz.GenerationCancelled"] = "Question generation stopped.",
            ["Quiz.GenerationFailedAfterRetries"] = "AI produced invalid facts 3 times. Select Create with AI to try again.",
            ["Quiz.NotEnoughMemory"] = "This model is too large for the device. Choose a smaller Gemma 4 E2B/E4B Q4 model.",
            ["Quiz.ModelRuntimeError"] = "This model could not run on the device. Choose a smaller Gemma 4 E2B/E4B Q4 model.",
            ["Quiz.WordProblemTitle"] = "Problem created by your AI teacher",
            ["Quiz.PresentedAnswer"] = "Proposed answer: {0} {1}",
            ["Quiz.SolutionTitle"] = "Solution"
        };

    public static bool TryGetValue(
        string key,
        string culture,
        out string value)
    {
        IReadOnlyDictionary<string, string> strings =
            culture.StartsWith(
                "vi",
                StringComparison.OrdinalIgnoreCase)
                ? Vietnamese
                : English;

        return strings.TryGetValue(
            key,
            out value!);
    }
}
